### ISSUE TITLE
outlier_predictions_ras_tp53_nf1.tsv output error

### ISSUE THREAD

**Issue by jharenza** [marislab/pdx-classification#15]
I believe this file should have 3 rows per sample (one for each classifier type and whether that sample is WT/altered for each pathway). Right now, that is not the case.

**Comment by gwaygenomics** [comment]
the file only includes samples that the classifier guessed incorrectly on. Specifically, if the classifier gave the sample a score above 0.5, but the sample was annotated as wild-type, the sample would be in this file. (likewise, a sample with a score below 0.5, but annotated as altered would be here too).

The data is sorted by classifier score, in other words, by confidence of incorrect assignment.

**Comment by gwaygenomics** [comment]
i think changing the name of the column `hugo_symbol` to `classifier_gene` may help clear this up

**Comment by jharenza** [comment]
ok, makes sense
